[package]
name = "suoi_rwin"
version = "0.1.0"
edition = "2021"

[dependencies]
gl = "0.14.0"
glfw = "*"

suoi_simp = { git = "https://github.com/ValynTyler/suoi_simp.git" }
suoi_types = { git = "https://github.com/ValynTyler/suoi_types.git" }
